export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_CLEAR = 'LOGIN_USER_CLEAR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
