export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_CLEAR = 'REGISTER_USER_CLEAR';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
